create table algorithms
(
    algorithm                                serial
        constraint algorithms_pk primary key,
    schema                                   integer               not null,
    commands                                 text                  not null,
    algorithm_dimension                      integer,
    description                              text,
    paint_dot                                boolean default false not null,
    paint_up_monochromatic                   boolean default false not null,
    paint_down_monochromatic                 boolean default false not null,
    paint_left_monochromatic                 boolean default false not null,
    paint_right_monochromatic                boolean default false not null,
    paint_square_upleftdown_monochromatic    boolean default false not null,
    paint_square_uprightdown_monochromatic   boolean default false not null,
    paint_square_rightdownleft_monochromatic boolean default false not null,
    paint_square_rightupleft_monochromatic   boolean default false not null,
    paint_square_leftdownright_monochromatic boolean default false not null,
    paint_square_leftupright_monochromatic   boolean default false not null,
    paint_square_downleftup_monochromatic    boolean default false not null,
    paint_square_downrightup_monochromatic   boolean default false not null,
    paint_diagonal_upleft_monochromatic      boolean default false not null,
    paint_diagonal_upright_monochromatic     boolean default false not null,
    paint_diagonal_downleft_monochromatic    boolean default false not null,
    paint_diagonal_downright_monochromatic   boolean default false not null,
    paint_l_upleft_monochromatic             boolean default false not null,
    paint_l_upright_monochromatic            boolean default false not null,
    paint_l_downleft_monochromatic           boolean default false not null,
    paint_l_downright_monochromatic          boolean default false not null,
    paint_l_leftup_monochromatic             boolean default false not null,
    paint_l_leftdown_monochromatic           boolean default false not null,
    paint_l_rightup_monochromatic            boolean default false not null,
    paint_l_rightdown_monochromatic          boolean default false not null,
    paint_zigzag_leftupdown_monochromatic    boolean default false not null,
    paint_zigzag_leftdownup_monochromatic    boolean default false not null,
    paint_zigzag_rightupdown_monochromatic   boolean default false not null,
    paint_zigzag_rightdownup_monochromatic   boolean default false not null,
    paint_zigzag_upleftright_monochromatic   boolean default false not null,
    paint_zigzag_uprightleft_monochromatic   boolean default false not null,
    paint_zigzag_downleftright_monochromatic boolean default false not null,
    paint_zigzag_downrightleft_monochromatic boolean default false not null,
    paint_up_polychromatic                   boolean default false not null,
    paint_down_polychromatic                 boolean default false not null,
    paint_left_polychromatic                 boolean default false not null,
    paint_right_polychromatic                boolean default false not null,
    paint_square_upleftdown_polychromatic    boolean default false not null,
    paint_square_uprightdown_polychromatic   boolean default false not null,
    paint_square_rightdownleft_polychromatic boolean default false not null,
    paint_square_rightupleft_polychromatic   boolean default false not null,
    paint_square_leftdownright_polychromatic boolean default false not null,
    paint_square_leftupright_polychromatic   boolean default false not null,
    paint_square_downleftup_polychromatic    boolean default false not null,
    paint_square_downrightup_polychromatic   boolean default false not null,
    paint_diagonal_upleft_polychromatic      boolean default false not null,
    paint_diagonal_upright_polychromatic     boolean default false not null,
    paint_diagonal_downleft_polychromatic    boolean default false not null,
    paint_diagonal_downright_polychromatic   boolean default false not null,
    paint_l_upleft_polychromatic             boolean default false not null,
    paint_l_upright_polychromatic            boolean default false not null,
    paint_l_downleft_polychromatic           boolean default false not null,
    paint_l_downright_polychromatic          boolean default false not null,
    paint_l_leftup_polychromatic             boolean default false not null,
    paint_l_leftdown_polychromatic           boolean default false not null,
    paint_l_rightup_polychromatic            boolean default false not null,
    paint_l_rightdown_polychromatic          boolean default false not null,
    paint_zigzag_leftupdown_polychromatic    boolean default false not null,
    paint_zigzag_leftdownup_polychromatic    boolean default false not null,
    paint_zigzag_rightupdown_polychromatic   boolean default false not null,
    paint_zigzag_rightdownup_polychromatic   boolean default false not null,
    paint_zigzag_upleftright_polychromatic   boolean default false not null,
    paint_zigzag_uprightleft_polychromatic   boolean default false not null,
    paint_zigzag_downleftright_polychromatic boolean default false not null,
    paint_zigzag_downrightleft_polychromatic boolean default false not null,
    paint_custom_pattern_monochromatic       boolean default false not null,
    paint_custom_pattern_polychromatic       boolean default false not null,
    fill_empty                               boolean default false not null,
    copy                                     boolean default false not null,
    repeat                                   boolean default false not null,
    mirror_cross_vertical                    boolean default false not null,
    mirror_cross_horizontal                  boolean default false not null,
    mirror_cells_vertical                    boolean default false not null,
    mirror_cells_horizontal                  boolean default false not null,
    mirror_commands_vertical                 boolean default false not null,
    mirror_commands_horizontal               boolean default false not null,
    constraint algorithms_pk
        primary key (algorithm)
);